# Generated by Django 5.0 on 2023-12-30 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracja', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pacjenci',
            fields=[
                ('numer_pac', models.IntegerField(primary_key=True, serialize=False)),
                ('imie', models.TextField(blank=True, null=True)),
                ('nazwisko', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pacjenci',
                'managed': False,
            },
        ),
    ]
