# Generated by Django 5.0 on 2023-12-30 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracja', '0004_pacjenci'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wizyta',
            fields=[
                ('numer_pacjenta', models.IntegerField(blank=True, null=True)),
                ('numer_lekarza', models.IntegerField(blank=True, null=True)),
                ('data_wizyty', models.TextField(primary_key=True, serialize=False)),
                ('koszt', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'wizyta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Zalecenia',
            fields=[
                ('numer_pacjenta', models.IntegerField(blank=True, null=True)),
                ('numer_lekarza', models.IntegerField(blank=True, null=True)),
                ('data_wizyty', models.TextField(primary_key=True, serialize=False)),
                ('koszt', models.IntegerField(blank=True, null=True)),
                ('recepta', models.IntegerField(blank=True, null=True)),
                ('szczegol', models.TextField(blank=True, null=True)),
                ('badania', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'zalecenia',
                'managed': False,
            },
        ),
    ]
